type SourceDrinkModel = {
  dateModified: String;
  idDrink: String;
  strAlcoholic: String;
  strCategory: String;
  strDrink: String;
  strDrinkDE: String;
  strDrinkES: String;
  strDrinkFR: String;
  strDrinkThumb: String;
  "strDrinkZH-HANS": String;
  "strDrinkZH-HANT": String;
  strGlass: String;
  strIBA: String;
  strIngredient1: String;
  strIngredient2: String;
  strIngredient3: String;
  strIngredient4: String;
  strIngredient5: String;
  strIngredient6: String;
  strIngredient7: String;
  strIngredient8: String;
  strIngredient9: String;
  strIngredient10: String;
  strIngredient11: String;
  strIngredient12: String;
  strIngredient13: String;
  strIngredient14: String;
  strIngredient15: String;
  strInstructions: String;
  strInstructionsDE: String;
  strInstructionsES: String;
  strInstructionsFR: String;
  "strInstructionsZH-HANS": String;
  "strInstructionsZH-HANT": String;
  strMeasure1: String;
  strMeasure2: String;
  strMeasure3: String;
  strMeasure4: String;
  strMeasure5: String;
  strMeasure6: String;
  strMeasure7: String;
  strMeasure8: String;
  strMeasure9: String;
  strMeasure10: String;
  strMeasure11: String;
  strMeasure12: String;
  strMeasure13: String;
  strMeasure14: String;
  strMeasure15: String;
  strVideo: String;
};

type SourceDrinkShortModel = {
  idDrink: String;
  strDrink: String;
  strDrinkThumb: String;
};

type SourceIngredientModel = {
  idIngredient: String;
  strDescription: String;
  strIngredient: String;
  strType: String;
};
